openapi: 3.0.3
info:
  title: STD23042 - TD1
  version: '1.0.3'
servers:
  - url: https://localhost.std23042.com
paths:
  /competitions:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
      responses:
        200:
          description: List of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateCompetition'
        required: true
      responses:
        200:
          description: List of created competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'

  /teams:
    get:
      parameters:
        - name: teamName
          in: query
          schema:
            type: string
          description: Filter teams by name
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created successfully

  /teams/{teamId}/competitions:
    post:
      summary: Associate a team with competitions
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: Competitions associated successfully

  /teams/{teamId}/players:
    get:
      summary: Get the list of players in a team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
        - name: playerName
          in: query
          schema:
            type: string
          description: Filter players by name
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      summary: Add players to a team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '201':
          description: Players added successfully

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
        location:
          type: string

    Team:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string

    Player:
      type: object
      properties:
        name:
          type: string
        number:
          type: integer
        strongFoot:
          type: string
          enum:
            - Left
            - Right
